[package]
name = "mihomo_api"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.182", features = ["derive"] }
serde_json = "1.0.104"
reqwest = "0.11.18"
tokio = {version= "1.29.1", features=["full"]}